// Generated by CoffeeScript 1.6.3
(function() {
  var HASH_CASH_NUM_BITS, HashCash, MAX_TESTS, resource, results, test, updateData;

  HASH_CASH_NUM_BITS = 19;

  MAX_TESTS = 100;

  HashCash = hashcash.HashCash;

  resource = "zvelo.com";

  results = {
    num: 0,
    duration: 0,
    min: void 0,
    max: void 0,
    stop: false
  };

  window.stop = function() {
    if (results.num >= MAX_TESTS) {
      return;
    }
    $("body").append("<p>stopping...</p>");
    return results.stop = true;
  };

  updateData = function(start, hashcash) {
    var averageDuration, duration, hc, str, valid;
    str = "<pre>" + ("test number: " + (results.num + 1) + "<br>") + ("hashcash: " + hashcash + "<br>") + ("sha: " + (HashCash.hash(hashcash)) + "<br>");
    hc = new HashCash(HASH_CASH_NUM_BITS);
    valid = hc.validate(hashcash);
    str += "valid: " + valid + "<br>";
    duration = (new Date() - start) / 1000;
    if ((results.min == null) || duration < results.min) {
      results.min = duration;
    }
    if ((results.max == null) || duration > results.max) {
      results.max = duration;
    }
    results.duration += duration;
    results.num += 1;
    averageDuration = results.duration / results.num;
    str += ("duration: " + duration + "<br>") + ("average: " + averageDuration + "<br>") + ("min: " + results.min + "<br>") + ("max: " + results.max + "<br>") + "</pre>";
    $("body").append(str);
    if (results.stop) {
      return $("body").append("<p>stopped</p>");
    } else if (results.num < MAX_TESTS) {
      return test();
    }
  };

  test = function() {
    var hc, start;
    if (!resource.length) {
      return;
    }
    start = new Date();
    hc = new HashCash(HASH_CASH_NUM_BITS, "../browser/hashcash_worker.min.js");
    return hc.generate(resource, function(hashcash) {
      return updateData(start, hashcash);
    });
  };

  test();

}).call(this);
