// Generated by CoffeeScript 1.6.3
(function() {
  var HashCash, browserGenerate, buildDate, childProcess, nextPos, nodeGenerate, numLeading0s, sha1, webWorkerGenerate;

  sha1 = require("./sha1");

  childProcess = require("child_process");

  numLeading0s = function(hex_str) {
    var curNum, num, pos, _i, _ref;
    num = 0;
    for (pos = _i = 0, _ref = hex_str.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; pos = 0 <= _ref ? ++_i : --_i) {
      curNum = parseInt(hex_str[pos], 16);
      if (isNaN(curNum)) {
        break;
      }
      switch (curNum) {
        case 0x0:
          num += 4;
          break;
        case 0x1:
          return num + 3;
        case 0x2:
        case 0x3:
          return num + 2;
        case 0x4:
        case 0x5:
        case 0x6:
        case 0x7:
          return num + 1;
        default:
          return num;
      }
    }
    return num;
  };

  buildDate = function(date) {
    if (typeof date === "string") {
      if (date.length !== 6) {
        return null;
      }
      return date;
    }
    if (typeof date !== "number") {
      return null;
    }
    return buildDate("" + date);
  };

  nodeGenerate = function(data, callback) {
    var worker;
    worker = childProcess.fork(__dirname + "/worker.js");
    worker.on("message", function(test) {
      worker.disconnect();
      return callback(test);
    });
    return worker.send(data);
  };

  webWorkerGenerate = function(data, callback) {
    var worker;
    worker = new Worker(data.file);
    worker.onmessage = function(event) {
      worker.terminate();
      return callback(event.data);
    };
    return worker.postMessage(data);
  };

  browserGenerate = function(data, callback) {
    var RUNTIME_MAX, TIMEOUT, timeoutFn;
    RUNTIME_MAX = 99;
    TIMEOUT = 1;
    timeoutFn = function() {
      var start;
      start = new Date();
      while (!((data.result != null) || (new Date() - start >= RUNTIME_MAX))) {
        HashCash.testSha(data);
      }
      if (data.result != null) {
        return callback(data.result);
      } else {
        return setTimeout(timeoutFn, TIMEOUT);
      }
    };
    return setTimeout(timeoutFn, TIMEOUT);
  };

  nextPos = function(str, pos) {
    pos.start = pos.end + 1;
    if (pos.start === str.length) {
      return false;
    }
    pos.end = str.indexOf(':', pos.start);
    if (pos.end === -1) {
      return false;
    }
    if (pos.end === pos.start) {
      return false;
    }
    return true;
  };

  HashCash = (function() {
    HashCash.VERSION = 1;

    HashCash.MIN_BITS = 16;

    HashCash.hash = sha1.hash;

    HashCash.genDate = function() {
      var dd, mm, now, yy;
      now = new Date();
      yy = ("0" + (now.getYear() - 100)).slice(-2);
      mm = ('0' + (now.getMonth() + 1)).slice(-2);
      dd = ('0' + now.getDate()).slice(-2);
      return "" + yy + mm + dd;
    };

    HashCash.buildString = function(parts) {
      var date, ret;
      ret = "";
      if (parts.version == null) {
        return ret;
      }
      ret += "" + parts.version + ":";
      if (parts.bits == null) {
        return ret;
      }
      ret += "" + parts.bits + ":";
      if (parts.date == null) {
        return ret;
      }
      date = buildDate(parts.date);
      if (date == null) {
        return ret;
      }
      ret += "" + date + ":";
      if (parts.resource == null) {
        return ret;
      }
      ret += "" + parts.resource + ":";
      if (parts.rand == null) {
        return ret;
      }
      ret += parts.rand;
      if (parts.counter == null) {
        return ret;
      }
      return ret += ":" + parts.counter;
    };

    HashCash.testSha = function(data) {
      var sha, test;
      test = "" + data.challenge + ":" + data.counter;
      sha = sha1.hash(test);
      if (numLeading0s(sha) >= data.bits) {
        data.result = test;
      } else {
        data.counter += 1;
      }
      return void 0;
    };

    HashCash.parse = function(str) {
      var counterEnd, data, pos;
      if (str == null) {
        return null;
      }
      data = {};
      pos = {
        start: 0,
        end: -1,
        length: function() {
          return this.end - this.start;
        }
      };
      if (!nextPos(str, pos)) {
        return null;
      }
      data.version = parseInt(str.substr(pos.start, pos.length()), 10);
      if (isNaN(data.version)) {
        return null;
      }
      if (!nextPos(str, pos)) {
        return null;
      }
      data.bits = parseInt(str.substr(pos.start, pos.length()), 10);
      if (isNaN(data.bits)) {
        return null;
      }
      if (!nextPos(str, pos)) {
        return null;
      }
      data.date = parseInt(str.substr(pos.start, pos.length()), 10);
      if (isNaN(data.date)) {
        return null;
      }
      if (!nextPos(str, pos)) {
        return null;
      }
      data.resource = str.substr(pos.start, pos.length());
      if (!data.resource.length) {
        return null;
      }
      if (!nextPos(str, pos)) {
        return null;
      }
      data.rand = str.substr(pos.start, pos.length());
      if (!data.rand.length) {
        return null;
      }
      nextPos(str, pos);
      counterEnd = (pos.end === -1 ? str.length : pos.end) - pos.start;
      data.counter = parseInt(str.substr(pos.start, counterEnd), 10);
      if (isNaN(data.counter)) {
        return null;
      }
      return data;
    };

    function HashCash(bits, workerFile) {
      this.bits = bits;
      this.workerFile = workerFile;
      if (this.bits < HashCash.MIN_BITS) {
        this.bits = HashCash.MIN_BITS;
      }
    }

    HashCash.prototype.generate = function(resource, callback) {
      var data, parts;
      parts = {
        version: HashCash.VERSION,
        bits: this.bits,
        date: HashCash.genDate(),
        resource: resource,
        rand: Math.random().toString(36).substr(2)
      };
      data = {
        file: this.workerFile,
        challenge: HashCash.buildString(parts),
        counter: 0,
        bits: parts.bits
      };
      /*
      Use different strategies to ensure the main javascript thread is not
      hung up while generating the HashCash
      
      1. Under Node, we use child_process
      2. In browsers that support it, use web workers
      3. In other browsers, use setTimeout
      */

      if (typeof window === "undefined" || window === null) {
        return nodeGenerate(data, callback);
      } else if ((typeof Worker !== "undefined" && Worker !== null) && (this.workerFile != null)) {
        return webWorkerGenerate(data, callback);
      } else {
        return browserGenerate(data, callback);
      }
    };

    HashCash.prototype.validate = function(str) {
      var data, now;
      if (str == null) {
        return false;
      }
      if (this.bits == null) {
        return false;
      }
      data = HashCash.parse(str);
      if (data == null) {
        return false;
      }
      if (data.bits < this.bits) {
        return false;
      }
      if (data.bits < HashCash.MIN_BITS) {
        return false;
      }
      if (data.version !== HashCash.VERSION) {
        return false;
      }
      now = HashCash.genDate();
      if (data.date < now - 1 || data.date > now + 1) {
        return false;
      }
      return numLeading0s(sha1.hash(str)) >= data.bits;
    };

    return HashCash;

  })();

  exports.HashCash = HashCash;

}).call(this);
