// Generated by CoffeeScript 1.6.3
(function() {
  var NodeTaskMaster, TaskMaster, TimeoutTaskMaster, WebTaskMaster, childProcess, hashcash, os,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  os = require("os");

  childProcess = require("child_process");

  hashcash = require("./hashcash");

  TaskMaster = (function() {
    TaskMaster.RANGE_INCREMENT = Math.pow(2, 15);

    function TaskMaster(_caller, id, _callback, _range) {
      this._caller = _caller;
      this.id = id;
      this._callback = _callback;
      this._range = _range;
    }

    TaskMaster.prototype._send = function(data) {
      this._spawn();
      if (this.sendFn == null) {
        return;
      }
      return this.sendFn(data);
    };

    TaskMaster.prototype._spawn = function() {
      if (this.worker != null) {
        return;
      }
      this.connect();
      return this.sendId();
    };

    TaskMaster.prototype.sendId = function() {
      return this._send({
        m: "id",
        id: this.id
      });
    };

    TaskMaster.prototype.sendData = function(data) {
      return this._send({
        m: "data",
        data: data
      });
    };

    TaskMaster.prototype._nextRange = function() {
      this._range.begin = this._range.end + 1;
      this._range.end = this._range.begin + TaskMaster.RANGE_INCREMENT - 1;
      return this._range;
    };

    TaskMaster.prototype._sendRange = function() {
      var range;
      range = this._nextRange();
      return this._send({
        m: "range",
        range: range
      });
    };

    TaskMaster.prototype._gotResult = function(id, result) {
      if (result == null) {
        return;
      }
      return this._callback.call(this._caller, result, id);
    };

    TaskMaster.prototype._gotMessage = function(msg) {
      if ((msg != null ? msg.m : void 0) == null) {
        return;
      }
      switch (msg.m) {
        case "request_range":
          return this._sendRange();
        case "result":
          return this._gotResult(msg.id, msg.result);
        case "console_log":
          return console.log("worker " + msg.id, msg.data);
      }
    };

    TaskMaster.prototype.stop = function() {
      if (this.worker == null) {
        return;
      }
      this.disconnect();
      delete this.worker;
      return delete this.sendFn;
    };

    return TaskMaster;

  })();

  NodeTaskMaster = (function(_super) {
    __extends(NodeTaskMaster, _super);

    NodeTaskMaster.NUM_WORKERS = os.cpus != null ? os.cpus().length : 0;

    function NodeTaskMaster(caller, id, callback, range) {
      NodeTaskMaster.__super__.constructor.call(this, caller, id, callback, range);
    }

    NodeTaskMaster.prototype.connect = function() {
      var me;
      this.worker = childProcess.fork(__dirname + "/worker.js");
      me = this;
      this.worker.on("message", function(data) {
        return me._gotMessage.call(me, data);
      });
      return this.sendFn = function(data) {
        return this.worker.send(data);
      };
    };

    NodeTaskMaster.prototype.disconnect = function() {
      return this.worker.disconnect();
    };

    return NodeTaskMaster;

  })(TaskMaster);

  WebTaskMaster = (function(_super) {
    __extends(WebTaskMaster, _super);

    WebTaskMaster.NUM_WORKERS = 4;

    function WebTaskMaster(caller, id, callback, range, file) {
      this.file = file;
      WebTaskMaster.__super__.constructor.call(this, caller, id, callback, range);
    }

    WebTaskMaster.prototype.connect = function() {
      var me;
      this.worker = new Worker(this.file);
      me = this;
      this.worker.onmessage = function(event) {
        return me._gotMessage.call(me, event.data);
      };
      return this.sendFn = function(data) {
        return this.worker.postMessage(data);
      };
    };

    WebTaskMaster.prototype.disconnect = function() {
      return this.worker.terminate();
    };

    return WebTaskMaster;

  })(TaskMaster);

  TimeoutTaskMaster = (function() {
    TimeoutTaskMaster.MAX_RUNTIME = 99;

    TimeoutTaskMaster.YIELD_TIME = 1;

    TimeoutTaskMaster.NUM_WORKERS = 1;

    function TimeoutTaskMaster(_caller, id, _callback) {
      this._caller = _caller;
      this.id = id;
      this._callback = _callback;
    }

    TimeoutTaskMaster.prototype.sendData = function(_data) {
      this._data = _data;
      delete this._stopFlag;
      return this.start();
    };

    TimeoutTaskMaster.prototype.start = function() {
      var me, startTime;
      startTime = new Date();
      while (!((this._stopFlag != null) || (this._data.result != null) || (new Date() - startTime >= TimeoutTaskMaster.MAX_RUNTIME))) {
        hashcash.HashCash.testSha(this._data);
      }
      if (this._stopFlag != null) {

      } else if (this._data.result != null) {
        return this._callback.call(this._caller, this._data.result);
      } else {
        me = this;
        return setTimeout((function() {
          return me.start.call(me);
        }), TimeoutTaskMaster.YIELD_TIME);
      }
    };

    TimeoutTaskMaster.prototype.stop = function() {
      return this._stopFlag = true;
    };

    return TimeoutTaskMaster;

  })();

  exports.TaskMaster = TaskMaster;

  exports.NodeTaskMaster = NodeTaskMaster;

  exports.WebTaskMaster = WebTaskMaster;

  exports.TimeoutTaskMaster = TimeoutTaskMaster;

}).call(this);
