// Generated by CoffeeScript 1.6.3
(function() {
  var Drone, HashCash, drone;

  HashCash = require("./hashcash").HashCash;

  if (typeof self !== "undefined" && self !== null) {
    self.console = {
      log: function() {
        var args;
        if (typeof drone === "undefined" || drone === null) {
          return;
        }
        args = Array.prototype.slice.call(arguments);
        return drone.sendFn({
          m: "console_log",
          id: drone.id != null ? drone.id : -1,
          data: args
        });
      }
    };
  }

  Drone = (function() {
    Drone.MAX_RUNTIME = 99;

    Drone.YIELD_TIME = 1;

    function Drone(sendFn) {
      this.sendFn = sendFn;
    }

    Drone.prototype.gotMessage = function(msg) {
      if (msg.m == null) {
        return;
      }
      switch (msg.m) {
        case "id":
          return this._gotId(msg.id);
        case "data":
          return this._gotData(msg.data);
        case "range":
          return this._gotRange(msg.range);
        case "stop":
          return this._stop();
      }
    };

    Drone.prototype._gotId = function(value) {
      if (value == null) {
        return;
      }
      return this.id = value;
    };

    Drone.prototype._gotData = function(value) {
      if (!((value != null) && (this.id != null))) {
        return;
      }
      delete this._stopFlag;
      this._data = value;
      return this._requestRange();
    };

    Drone.prototype._gotRange = function(value) {
      if (!((value != null) && (this.id != null) && !this._stopped())) {
        return;
      }
      this._range = value;
      this._data.counter = this._range.begin;
      return this.start();
    };

    Drone.prototype._requestRange = function() {
      if (!((this.id != null) && !this._stopped())) {
        return;
      }
      return this.sendFn({
        m: "request_range",
        id: this.id
      });
    };

    Drone.prototype._sendResult = function() {
      if (!((this._data.result != null) && (this.id != null) && !this._stopped())) {
        return;
      }
      this._stop();
      return this.sendFn({
        m: "result",
        id: this.id,
        result: this._data.result
      });
    };

    Drone.prototype._stop = function() {
      return this._stopFlag = true;
    };

    Drone.prototype._stopped = function() {
      return this._stopFlag != null;
    };

    Drone.prototype.start = function() {
      var me;
      if (!((this._data != null) && (this._range != null) && !this._stopped())) {
        return;
      }
      while (!((this._data.result != null) || this._data.counter === this._range.end)) {
        HashCash.testSha(this._data);
      }
      if (this._data.result != null) {
        me = this;
        return process.nextTick(function() {
          return me._sendResult.call(me);
        });
      } else {
        return this._requestRange();
      }
    };

    return Drone;

  })();

  if (typeof self !== "undefined" && self !== null) {
    drone = new Drone(function(data) {
      return self.postMessage(data);
    });
    self.onmessage = function(event) {
      return drone.gotMessage(event.data);
    };
  } else {
    drone = new Drone(function(data) {
      return process.send(data);
    });
    process.on("message", function(data) {
      return drone.gotMessage(data);
    });
  }

}).call(this);
